name: Test

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Install QEMU, NASM (ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system-x86 nasm
      - name: Install QEMU, NASM (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install qemu nasm
      - name: Install QEMU, NASM (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install qemu --version 2021.12.15
          echo "C:\Program Files\qemu" >> $GITHUB_PATH
          choco install nasm
          echo "C:\Program Files\NASM" >> $GITHUB_PATH
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Rustup (apply rust-toolchain.toml)
        run: rustup show
      - name: Build dev profile
        run: cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit --package rusty_demo
      - name: Build loader
        working-directory: loader
        run: cargo xtask build --arch x86_64 --release
      - name: Test dev profile
        run: |
          qemu-system-x86_64 -display none -smp 1 -m 128M -serial stdio \
            -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand \
            -kernel loader/target/x86_64/release/rusty-loader \
            -initrd target/x86_64-unknown-hermit/debug/rusty_demo
      - name: Build release profile
        run:
          cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit --package rusty_demo --release
      - name: Test release profile
        run: |
          qemu-system-x86_64 -display none -smp 1 -m 128M -serial stdio \
            -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand \
            -kernel loader/target/x86_64/release/rusty-loader \
            -initrd target/x86_64-unknown-hermit/release/rusty_demo
      - name: Build httpd with DHCP support
        run:
          cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit --package httpd --features dhcpv4
      - name: Build httpd without DHCP support
        run:
          cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit --package httpd
